controllers/internal/statefuljob/job.go
controllers/internal/statefuljob/job_test.go

Previously, we only injected these in the containers (not initcontainers)

fix: Inject volumes and env vars into init containers

---

README.md
config/samples/cosmos_v1alpha1_statefuljob.yaml
controllers/internal/statefuljob/job.go
controllers/internal/statefuljob/job_test.go

This was a result of a pairing session. The StatefulJob is assuming too much on what the VolumeSnapshot contains. 
The VolumeSnapshot may be from any PVC, not just ones created from CosmosFullNode.

refactor(StatefulJob): Remove container volume mounts

---

controllers/internal/statefuljob/active_job_test.go
controllers/internal/statefuljob/job_test.go
controllers/internal/statefuljob/pvc_test.go
controllers/internal/statefuljob/resource.go
controllers/internal/statefuljob/resource_test.go

This is a backwards breaking change. (As a reminder, StatefulJob is alpha.)
The motivation for this change is no other k8s controllers prefix in this manner, so I'm moving to k8s conventions. 
We only have one deployment using StatefulJob so far, so I will manually babysit that one.
The result of this change is a potential 2 job/pvc combos due to not cleaning up the resources with the now deprecated prefix `stateful-job`. I'll manually clean up the old resources.

refactor(StatefulJob): Remove prefix from resource names

---

api/v1/cosmosfullnode_types.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
controllers/internal/fullnode/service_builder.go
controllers/internal/fullnode/service_builder_test.go
controllers/internal/fullnode/service_control_test.go

Each p2p service creates external resources on the cloud provider (ip addresses, load balancers, etc). Those are not free. So I'm opting to prioritize infra costs and quotas over more p2p peers. 
The user can optionally increase this setting if they want to expose more p2p peers.

refactor(CosmosFullNode): Change p2p service default from 3 to 1

---

README.md

Because of other Strangelove priorities, there is likely chance the ScheduledVolumeSnapshot feature will not be complete until beginning Q1.

docs: Minor change to state of roadmap in readme

---

api/v1alpha1/scheduledvolumesnapshot_types.go
config/crd/bases/cosmos.strange.love_scheduledvolumesnapshots.yaml
controllers/internal/volsnapshot/vol_snapshot_control.go
controllers/internal/volsnapshot/vol_snapshot_control_test.go
controllers/scheduledvolumesnapshot_controller.go
go.mod

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/164
The limit default is 3 (arbitrarily chosen). I was trying to balance between usefulness and costs. 
I'm letting this new snapshot feature run over the weekend every 15 minutes as a torture test.

feat(ScheduledVolumeSnapshot): Delete snapshots that exceed limit 

---

api/v1/cosmosfullnode_types.go
api/v1alpha1/scheduledvolumesnapshot_types.go
api/v1alpha1/statefuljob_types.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
config/crd/bases/cosmos.strange.love_scheduledvolumesnapshots.yaml
config/crd/bases/cosmos.strange.love_statefuljobs.yaml

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/175
Controls how k8s clients (like kubectl) pretty print columns. 
Now it will show something like this:

feat: Add printer columns to all CRDs

---

controllers/internal/fullnode/pod_builder.go
controllers/internal/fullnode/pod_builder_test.go

Validator sentries do not serve traffic like RPC nodes. (Or at least, they shouldn't for safety.) An outsider should not be able to query or transact with a sentry. Only p2p is exposed.  K8s readiness probes are for serving traffic, which isn't a use case for sentries.
In our case, with horcrux and remote signers, we have a chicken or egg problem. Tendermint requires immediate connection to the remote signer. However, the chain process will not be ready until that connection is made.
We use k8s services for a stable IP for horcrux. Therefore, we cannot use readiness probes for sentries because k8s will never add the pod to the service.

fix: Remove readiness probes for sentries

---

controllers/internal/fullnode/configmap_builder.go
controllers/internal/fullnode/configmap_builder_test.go

Sets this default in `config.toml`.
```toml
[tx_index]
indexer = "null"
```
An oversight (because the Sentry feature was a bit rushed to meet a deadline).
Don't need to index on sentries which shouldn't be exposed to the internet for queries. 
Fyi, the user can always override these default values.

fix: Don't index by default for sentries

---

internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go
internal/healthcheck/healtcheck.go

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/185
Deprecates and removes the ignite-health-check 3rd party container.

feat(CosmosFullNode): Use native health check for probes

---

controllers/scheduledvolumesnapshot_controller.go
internal/volsnapshot/fullnode_control.go
internal/volsnapshot/fullnode_control_test.go

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/196
After some "shower thinking", this is the better solution. To check the fullnode's status vs. its actual pods. This way, if fullnode has been scaled down, the ScheduledVolumeSnapshot still progresses. It only cares about that status being set correctly.

fix(ScheduledVolumeSnapshot): Restore pod edge case

---

internal/cosmos/pod_filter.go
internal/cosmos/pod_filter_test.go
internal/volsnapshot/vol_snapshot_control.go
internal/volsnapshot/vol_snapshot_control_test.go

This is to fix odd behavior when you've disabled readiness probes (such as with sentries). 
If we look at just the pod's ready state, there's a chance the controller causes downtime. 
E.g. Disabled readiness probes. 3 sentries. Only 1 is in-sync (not catching up). The ScheduledVolumeSnapshot controller would have deleted the sole sentry that's in sync to create the snapshot.
Now we make sure any pod candidates are in-sync.

refactor(ScheduledVolumeSnapshot): Find candidate selects pods that are in-sync

---

internal/fullnode/pvc_control.go
internal/fullnode/pvc_control_test.go

Fixes an edge case. If you created then quickly resized the PVC, the resize may have been missed by the controller. 
Manually tested in a test cluster.

fix(CosmosFullNode): Requeue if updated pvc is not bound yet

---

healtcheck_cmd.go
internal/fullnode/pod_builder.go
internal/healthcheck/disk_usage.go
internal/healthcheck/disk_usage_test.go

Supports https://github.com/strangelove-ventures/cosmos-operator/issues/18
We have to explicitly ask for stats on the PVC mount path to get accurate stats. Manual testing surfaced this bug. 
Given PVC capacity 500 Gi (note, the power of 2 unit, Gibibytes), the endpoint returns:
```sh
{"all_bytes":527295578112,"free_bytes":330858098688}
```
The `all_bytes` is equal to 491 Gi (Gibibytes). So it's close enough.
Using the root path `"/"` was giving total space of ~100G which is the ephemeral disk on the node.
The used spaced `all_bytes - free_bytes` percentage also matches with `df` in the container.
```
df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/sdb             514937088 192650484 322270220  37% /home/operator
```
From the healtcheck endpoint `/disk`.
``` …
```

fix(CosmosFullNode): Healthcheck disk stats directory

---

internal/fullnode/genesis.go
internal/fullnode/genesis_test.go
internal/fullnode/pod_builder.go

The genesis check was failing on noble.  It was giving an error saying `rm` not found.  @agouin and I reworked it to follow the genesis check we used in the infra in the past.

paired with andrew to rework genesis check

---

controllers/cosmosfullnode_controller.go
controllers/scheduledvolumesnapshot_controller.go
controllers/statefuljob_controller.go
internal/cosmos/pod_filter.go
internal/fullnode/configmap_control.go
internal/fullnode/configmap_control_test.go
internal/fullnode/pod_control.go
internal/fullnode/pod_control_test.go
internal/fullnode/pvc_control.go
internal/fullnode/pvc_control_test.go
internal/fullnode/service_control.go
internal/fullnode/service_control_test.go
internal/kube/reporter.go
internal/test/mock_reporter.go
internal/volsnapshot/vol_snapshot_control.go
internal/volsnapshot/vol_snapshot_control_test.go

Supports https://github.com/strangelove-ventures/cosmos-operator/issues/18
Sometimes you want to just log, sometimes you want to record an event so it appears in `kubectl describe` and sometimes you want to do both. 
This abstraction simplifies the above without needing to rely on concrete types. 
I confirmed the kube API already prevents . Now we log and record it as an event.

refactor: Add abstraction for simplifying logging and event recording

---

internal/fullnode/genesis.go
internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go

On a mainnet deployment using statesync (snapshots were not an option), the logs reported this error:
```
ERR State sync failed err="failed to create chunk queue: unable to create temp dir for state sync chunks: stat /tmp: no such file or directory" module=statesync
```
What's odd is a previous testnet deployment with the same chain was able to statesync. The root cause is likely permissions.
This PR explicitly mounts `/tmp` as an emptyDir thereby leveraging the pod's `securityContext` to set appropriate perms. 
I tested on the mainnet deployment and statesync worked again. 
Exhausting the emptyDir if lots of data is saved there.

fix(CosmosFullNode): Statesync requires /tmp directory

---

internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go

Supports https://github.com/strangelove-ventures/cosmos-operator/issues/18
In the future, the operator will make requests to pods over the healthcheck port. Therefore, we require the sidecar to always be present. Originally removed because sentries do not have probes. 
The sidecar will not have probes (as unit tests prove).

refactor(CosmosFullNode): Restore healtcheck sidecar container

---

controllers/cosmosfullnode_controller.go
controllers/scheduledvolumesnapshot_controller.go
controllers/selfhealing_controller.go
healtcheck_cmd.go
internal/fullnode/client.go
internal/fullnode/mock_test.go
internal/fullnode/p2p.go
internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go
internal/fullnode/pod_disk_usage.go
internal/fullnode/pod_disk_usage_test.go
internal/healthcheck/client.go
internal/healthcheck/client_test.go
internal/healthcheck/healtchcheck.go
main.go

Phase 2 of https://github.com/strangelove-ventures/cosmos-operator/issues/18
Introduces the SelfHealingReconciler which also watches a CosmosFullNode. 
Additionally:
* Uses upgraded healtcheck image for the sidecar so we get the `/disk` endpoint.
* Checks for invalid disk usage responses of 0 free bytes (which causes a divide by 0)
* Collects disk usage for all PVCs. 
* Rounds disk usage to nearest integer (instead of truncating)
Temporarily logs disk usage, such as:
```
manager 2023-03-08T18:18:04Z    info    SelfHealing    Found pod disk usage    {"controller": "cosmosfullnode", "controllerGroup": "cosmos.strange.love", "controllerKind": "CosmosFullNode", "CosmosF
ullNode": {"name":"cosmoshub","namespace":"default"}, "namespace": "default", "name": "cosmoshub", "reconcileID": …
```

feat(CosmosFullNode): SelfHealing collects disk percentages

---

internal/fullnode/pvc_builder.go
internal/fullnode/pvc_builder_test.go

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/18
When we build PVCs, we take the greater of storage set by the user or set by the pvc auto scaler.

feat(CosmosFullNode): PVC builder uses auto scale quantity

---

.github/workflows/go.yaml
Dockerfile
go.mod

Go is on 1.20.2. Time to upgrade. Loosely part of https://github.com/strangelove-ventures/cosmos-operator/issues/21, so that we have the latest patches to crypto packages.

refactor: Upgrade Go to 1.20

---

api/v1/cosmosfullnode_types.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
controllers/cosmosfullnode_controller.go

Starts https://github.com/strangelove-ventures/cosmos-operator/issues/21
Adding more fine-grained phases allows the user to understand what's happening with the operator. 
For this story, it lets the user know p2p services are still being provisioned. Therefore, it lets the user know that they should not use the peer ids yet.

feat: Add WaitingForP2PServices fullnode phase

---

internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go

Addresses https://github.com/strangelove-ventures/cosmos-operator/issues/244, but does not solve it. We should still handle the error case if the VolumeSnapshot fails. 
We can now inject other volumes into pods. This means we cannot rely on the order of volumes when fetching the PVC name.

fix: Don't rely on volume order when finding PVC name

---

internal/cosmos/pod_filter_test.go
internal/fullnode/pvc_auto_scaler_test.go
internal/kube/labels_test.go
internal/kube/volume_snapshot_test.go
internal/volsnapshot/vol_snapshot_control_test.go

`main` branch was failing CI lint stage. 
Per Go 1.20 documentation:
```
// Deprecated: Programs that call Seed and then expect a specific sequence
// of results from the global random source (using functions such as Int)
// can be broken when a dependency changes how much it consumes
// from the global random source. To avoid such breakages, programs
// that need a specific result sequence should use NewRand(NewSource(seed))
// to obtain a random generator that other packages cannot access.
```
`lo.Shuffle` uses the global source. Only used for tests, so I left as-is. 
It's odd CI on PRs is not catching this...

fix(lint): Remove rand.Seed, use local source if available

---

.github/workflows/release.yaml
Dockerfile
Makefile
internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go
internal/version/version.go
main.go

The healthcheck sidecar now uses the version passed in via ldflags. 
This prevents manual steps of 1) releasing a new version 2) manually updating the tag in pod builder to that version and 3) releasing yet another version so the sidecar is up to date. 
Need to make sure the release GH workflow works. I'll push a release candidate soon and debug if necessary.

feat(CosmosFullNode): Healthcheck sidecar uses build version

---

internal/fullnode/pvc_builder.go
internal/fullnode/pvc_builder_test.go
internal/fullnode/pvc_control.go
internal/fullnode/pvc_control_test.go

Moves PVC reconciliation to the new diff. The only one left after this is pods.

refactor(CosmosFullNode): PVCs use new diffing

---

README.md
docs/quick_start.md
docs/scheduled_volume_snapshot.md
docs/stateful_job.md

This was based on internal feedback from outside teams wanting to test the operator.

docs: Break apart readme into smaller docs; add quick start guide

---

controllers/cosmosfullnode_controller.go
controllers/selfhealing_controller.go
go.mod
internal/cosmos/pod_filter.go
internal/cosmos/pod_filter_test.go
internal/fullnode/pvc_auto_scaler.go
internal/fullnode/pvc_disk_usage.go
internal/kube/reporter.go
internal/test/mock_reporter.go
internal/volsnapshot/vol_snapshot_control.go
internal/volsnapshot/vol_snapshot_control_test.go

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/272
Introduces a `Debug` log method. Removes `multierr` in favor of the now native `errors.Join`.

fix: Reduce some logging and event noise

---

api/v1/cosmosfullnode_types.go
controllers/cosmosfullnode_controller.go
internal/fullnode/p2p.go
internal/fullnode/p2p_test.go
internal/fullnode/service_builder.go
internal/fullnode/service_builder_test.go
internal/fullnode/service_control_test.go

Starts https://github.com/strangelove-ventures/cosmos-operator/issues/42
We now create a p2p service for each pod. But only some of them are of type: LoadBalancer depending on how the user configures the spec.
The long-term plan (in a future PR) is that we will use the service DNS names to be the private peers. 
We could use the pod IPs directly. However, this will cause potentially infinite thrashing. As pods are destroyed/created with new IPs, the config.toml will need to be updated for each new set of pod IPs which in turn will cause a pod destroy/recreate. Services give us a stable address (i.e. the DNS name).

feat(CosmosFullNode): Create p2p services for each pod

---

api/v1alpha1/scheduledvolumesnapshot_types.go
config/crd/bases/cosmos.strange.love_scheduledvolumesnapshots.yaml
controllers/scheduledvolumesnapshot_controller.go

Starts https://github.com/strangelove-ventures/cosmos-operator/issues/275
This changes the default where removing the pod must be configured by the user. The new default behavior is to keep the pod and create a snapshot as the pod is still reading/writing to the PVC. As a reminder, ScheduledVolumeSnapshot is still alpha, so breaking changes are allowed. 
When we're not removing a pod, it doesn't make sense to care about if pods are in sync or not. Synced pods are a concern when removing a pod because we do not want to cause downtime. 
A followup PR will address this limitation.

feat(ScheduledVolumeSnapshot): Take snapshot without removing pod

---

internal/cosmos/cache_controller.go
internal/cosmos/cache_controller_test.go
internal/cosmos/status_collection.go
internal/cosmos/status_collection_test.go

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/273
The cache controller always uses the most recent pods and collects cached Comet statuses only. 
This prevents stale cache errors such as:
* Taking down all pods on a rollout because the cached pods are all ready. 
* Prevents scenarios where pods have been added or removed since the time the pods have been cached.

fix: Only use current pods when fetching cached data

---

internal/cosmos/cache_controller_test.go

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/320
The data race was inherent only to the tests. 
I'm not sure why I was testing that last use case (may have been a mistake). We test zero state in another subtest which should cover our bases there.
Stress test results:
```
❯ go test -race -c ./internal/cosmos && stress ./cosmos.test
5s: 733 runs so far, 0 failures
10s: 1515 runs so far, 0 failures
15s: 2293 runs so far, 0 failures
20s: 3065 runs so far, 0 failures
25s: 3814 runs so far, 0 failures
30s: 4583 runs so far, 0 failures
35s: 5356 runs so far, 0 failures
40s: 6101 runs so far, 0 failures
45s: 6861 runs so far, 0 failures
50s: 7640 runs so far, 0 failures
55s: 8375 runs so far, 0 failures
1m0s: 9108 runs so far, 0 failures
1m5s: 9851 runs so far, 0 failures …
```

fix(CacheController): Data race in test

---

controllers/selfhealing_controller.go

This message was redundant, so I improved it.
```
Events:
Type    Reason                 Age                From         Message
----    ------                 ----               ----         -------
Normal  HeightDriftMitigation  10m (x3 over 12m)  SelfHealing  Height drift mitigation deleted pod
```

refactor(SelfHeal): Improve height drift mitigation logging

---

controllers/selfhealing_controller.go

Because otherwise the log line is super long and bad DX as it prints the entire pod object.

fix(CosmosFullNode): Log pod name not the entire pod

---

api/v1alpha1/scheduledvolumesnapshot_types.go
controllers/scheduledvolumesnapshot_controller.go
controllers/statefuljob_controller.go
main.go

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/326
Without VolumeSnapshot CRDs, the entire operator process crashes.
Since VolumeSnapshots for supporting controllers (not for CosmosFullNode), I don't think crashing is appropriate. Instead it will run and report errors in appropriate places.

fix: Don't require VolumeSnapshot CRDs to run the manager

---

internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go

When pods are not shut down cleanly, tmp dir is not wiped, causing failure to start up again.
Requires another init container, but it uses the same infra-toolkit image, so negligible time is added to pod init routine.
Resolves #329

add fresh init container to cleanup tmp dir

---

README.md

Accidentally forgot an important word.

docs: Don't omit "all" in README

---

api/v1/cosmosfullnode_types.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
config/samples/cosmos_v1_cosmosfullnode_full.yaml
healtcheck_cmd.go
internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go
internal/fullnode/pvc_disk_usage.go
internal/fullnode/pvc_disk_usage_test.go
internal/healthcheck/client.go
internal/healthcheck/client_test.go
internal/healthcheck/disk_usage.go
internal/healthcheck/disk_usage_test.go

Closes https://github.com/strangelove-ventures/cosmos-operator/issues/341
There's been too many instances where chains still persist data outside of the `--home` flag. 
Notably: Osmosis, DYDX, and now DVPN/Sentinel.
So we can't rely on chains to respect the user's intentions. 
This feature allows the user to optionally configure the chain home. 
Unfortunately, we can't reliably derive the home path because no chains use a common convention.

feat(CosmosFullNode): Allow configuring the chain home directory

---

.github/workflows/manifests.yaml
api/v1/cosmosfullnode_types.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
internal/fullnode/build_pods.go
internal/fullnode/build_pods_test.go
internal/fullnode/pod_builder.go

Allow user to override the image for a specific pod, useful if pods are at different sync heights during initial sync.

Add image override

---

internal/fullnode/build_pods.go
internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go

This PR adds hostname & subdomain to pods on creation (similar to how stateful sets do).
This is needed for a headless service to have podname.servicename... DNS resolution (instead of just servicename).
ala
`
root@harpoon-horcrux-1:/# host harpoon-0.harpoon
harpoon-0.harpoon.cosmos.svc.cluster.local has address 10.0.9.240
root@harpoon-horcrux-1:/# host harpoon-1.harpoon
harpoon-1.harpoon.cosmos.svc.cluster.local has address 10.0.7.151
root@harpoon-horcrux-1:/# host harpoon-2.harpoon
harpoon-2.harpoon.cosmos.svc.cluster.local has address 10.0.8.192
root@harpoon-horcrux-1:/# host harpoon
harpoon.cosmos.svc.cluster.local has address 10.0.7.151
harpoon.cosmos.svc.cluster.local has address 10.0.9.240
harpoon.cosmos.svc.cluster.local has address 10.0.8.192
`
before this patch only the last …

feat: add subdomain/hostname to pods created

---

internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go

The periodic db version check sidecar should not be added when spec.chain.versions is not populated

Backwards compatibility when spec.chain.versions is not populated

---

api/v1/cosmosfullnode_types.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
internal/fullnode/build_pods.go
internal/fullnode/pod_builder.go
internal/fullnode/pod_control_test.go

If `spec.chain.versions` is populated, then `spec.podTemplate.image` is not required

Dont require podspec image

---

.github/workflows/release.yaml

Without the tag, it was running the image vulnerability scan on the latest image, which is only published on release tags.

Run trivy on image in PR

---

api/v1/cosmosfullnode_types.go
api/v1/self_healing_types.go
api/v1/zz_generated.deepcopy.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
controllers/cosmosfullnode_controller.go
internal/fullnode/mock_test.go
internal/fullnode/pod_builder_test.go
internal/fullnode/pvc_auto_scaler.go
internal/fullnode/pvc_auto_scaler_test.go
internal/fullnode/pvc_builder.go
internal/fullnode/pvc_builder_test.go
internal/fullnode/pvc_control.go
internal/fullnode/pvc_control_test.go

Main motivation: 
- minimize created PVC size and expand only as needed on a per-PVC basis. Previously, it was always creating new PVCs with the latest auto scaled size, which meant that PVCs could not shrink on re-creation without re-creating the entire CosmosFullNode resource.
- Allow autoDataSource to work with snapshots that are node-local
Changes:
- New PVCs will not use the `status.selfHealing` size, but rather the maximum of: {  `spec.volumeClaimTemplate.resources.storage`,  `spec.instanceOverrides[instanceName].volumeClaimTemplate.resources.storage`, or data source size, if a data source is configured either explicitly or via `autoDataSource` }
- `status.selfHealing` is now maintained on a per-instance basis, so that storage expansion is minimized. Pods can have different storage …

PVC auto scale on a per ordinal basis

---

cmd/versioncheck.go
internal/fullnode/rbac_builder.go
internal/fullnode/rbac_builder_test.go

The `version-check` initContainer and `version-check-term` container should use the `Patch` operation instead of `Update` to avoid race conditions that can result in errors logs such as:
```
failed to patch status: Operation cannot be fulfillfed on cosmosfullnodes.cosmos.strange.love: the object has been modified
```
This is only seen intermittently, and the instance will automatically recover on the next restart.
Since the version check is a synchronous operation per instance, we don't need to worry about multiple concurrent writers to the status.height of the specific instance. The RPC status.height updates will only occur after this when the node is started.

version check patch

---

controllers/cosmosfullnode_controller.go

When we are at the upgrade height, we are working on the upgrade height, so the last committed block will be one less than the upgrade height.

Fix off by one

---

api/v1/cosmosfullnode_types.go
api/v1/zz_generated.deepcopy.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go

Allow providing additional args to the chain init command using `spec.chain.additionalInitArgs []string`

Support extra init args

---

internal/fullnode/pod_builder.go
internal/fullnode/pod_builder_test.go

move `--chain-id` flag after init, required for some chains like axelar

Chain ID flag order

---

config/crd/kustomization.yaml
config/crd/patches/webhook_in_cosmosfullnodes.yaml
config/crd/patches/webhook_in_hostedsnapshots.yaml
config/crd/patches/webhook_in_scheduledvolumesnapshots.yaml
config/default/kustomization.yaml
config/default/manager_auth_proxy_patch.yaml
config/default/manager_config_patch.yaml
config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_role_binding.yaml
config/rbac/auth_proxy_service.yaml
config/rbac/leader_election_role_binding.yaml
config/rbac/role_binding.yaml
config/rbac/service_account.yaml

- Use patches instead of deprecated patchesStrategicMerge
- Remove hardcoded namespace from resources This is automatically added by the config kustomization. Having it requires overlays to specify `namespace: system` or others in their `patches: target` which is confusing.
Created a dummy config kustomization and tested that allow following scenarios result in the same kustomize build
- Specifying the namespace: `example-ns` 
- Removing the namespace (results in exactly the same manifests, but with `cosmos-operator-system` as namespace ofc)
- Removing the `target` from the patch
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-ns
resources:
- /path/to/cosmos-operator/config/default
patches:
- target:
kind: Deployment
name: controller-manager …
```

fix(kube): cleanup config manifests

---

internal/fullnode/build_pods.go
internal/fullnode/pod_builder.go

An override image for an initContainer was not taking place due to chain versions getting priority

Apply strategic overrides after image is set

---

config/samples/cosmos_v1_cosmosfullnode_penumbra.yaml

- using current version of penumbra
- getting config from running RPC node
- being a fullnode, not a sentry

update penumbra example for mainnet

---

docs/quick_start.md

`quick_start.md Typo fix`
This pull request fixes a minor typo in the `quick_start.md` file:
- Corrected "kuberentes" to "kubernetes" for improved clarity and accuracy.

docs: fix typo in quick_start.md

---

main.go

Moves the listen and serve on the pprof endpoint into the if statement that guards starting profiling.

chore: Move pprof server listener start to if check for profiling

---

api/v1/cosmosfullnode_types.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
internal/fullnode/rbac_builder.go
internal/fullnode/role_binding_control.go
internal/fullnode/role_control.go
internal/fullnode/service_account_control.go

Enable providing service account externally for version check container to publish height to cosmosfullnode status

feat: allow external service account for pods

---

internal/fullnode/pod_builder.go

Many of our internal selectors depend on the `app.kubernetes.io/name` label pointing to the cosmos nodes, so remove from the additionalVersionedPods.

fix: unique name label on additionalVersionedPods

---

api/v1/cosmosfullnode_types.go
config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
internal/fullnode/pod_builder.go

`preferSameNode` on the `additionalVersionedPods` spec will prefer scheduling the pods on the same node as the main pod if set to true.

feat: allow prefer scheduling additional pods on same node as main pods

---

Dockerfile

https://musl.cc/ No longer accepts downloads from github actions
Downloaded toolchain and uploaded to our s3 bucket as a temporary fix.

Use musl toolchain from SL s3 bucket

---

internal/fullnode/service_builder.go
internal/fullnode/service_builder_test.go

- Fixes port mismatches between container ports and service ports when users configure custom `rpcListenAddress` or `p2pListenAddress`
- **service_builder.go:61**: Changed `Port: p2pPort,` to `Port: crd.Spec.ChainSpec.Comet.P2PPort(),`
- **service_builder.go:151**: Changed `Port: rpcPort,` to `Port: crd.Spec.ChainSpec.Comet.RPCPort(),`
- **service_builder_test.go**: Updated tests to use dynamic ports instead of hardcoded values

fix: use dynamic ports from CometConfig in service builder
