strangelove-ventures/cosmos-operator

- README.md
Progresses https://github.com/strangelove-ventures/cosmos-operator/issues/129
> docs: Add standard badges to README

- README.md
Progresses https://github.com/strangelove-ventures/cosmos-operator/issues/129
> docs: Update README with benefits and roadmap

- .github/workflows/go.yaml
- Dockerfile
- go.mod
> refactor: Upgrade Go to 1.19.3

- README.md
Part of https://github.com/strangelove-ventures/cosmos-operator/issues/151
> docs: Update readme for ScheduledVolumeSnapshots

- .github/workflows/release.yaml
Detect out of date/vulnerable packages in the docker container, can fail if it finds issues, but currently just warns.
> add trivy vulnerability scanning

- Makefile
- api/v1/cosmosfullnode_types.go
- api/v1/self_healing_types.go
- api/v1alpha1/scheduledvolumesnapshot_types.go
- api/v1alpha1/statefuljob_types.go
- controllers/cosmosfullnode_controller.go
- controllers/selfhealing_controller.go
- internal/fullnode/labels.go
- internal/fullnode/pvc_auto_scaler_test.go
- internal/statefuljob/labels.go
- internal/volsnapshot/vol_snapshot_control.go
- main.go
Aids with https://github.com/strangelove-ventures/cosmos-operator/issues/231
Literal strings were repeated everywhere.
> refactor: Add controller name constants

- config/rbac/role.yaml
- controllers/cosmosfullnode_controller.go
- internal/fullnode/configmap_control.go
- internal/fullnode/mock_test.go
- internal/fullnode/node_key_control.go
- internal/fullnode/node_key_control_test.go
Progresses https://github.com/strangelove-ventures/cosmos-operator/issues/21
We now save the node keys as secrets, and once saved they should not change. 
We do not use them yet, however.
> feat(CosmosFullNode): Save node key secrets

- internal/fullnode/node_key_builder.go
- internal/fullnode/pod_builder.go
- internal/fullnode/pod_builder_test.go
Progresses https://github.com/strangelove-ventures/cosmos-operator/issues/21
We mount the node keys into the containers.
> feat(CosmosFullNode): Mount node keys into main container

- healtcheck_cmd.go
- internal/fullnode/pod_builder.go
- internal/fullnode/pod_builder_test.go
- internal/fullnode/pvc_disk_usage.go
- internal/fullnode/pvc_disk_usage_test.go
A regression. Forgot SelfHeal feature needs it. 
Closes https://github.com/strangelove-ventures/cosmos-operator/issues/260
> fix(CosmosFullNode): Add back the chain home volume mount to healtcheck sidecar

- .github/workflows/go.yaml
- internal/fullnode/configmap_control.go
- internal/fullnode/ptr.go
- internal/fullnode/service_control.go
PRs were not catching lint failures and instead the main branch was failing.
> fix: CICD linting

- internal/fullnode/pod_builder.go
- internal/fullnode/pod_builder_test.go
Followup to https://github.com/strangelove-ventures/cosmos-operator/issues/260
> refactor(CosmosFullNode): Healthcheck sidecar chain home mount readonly

- controllers/cosmosfullnode_controller.go
- internal/fullnode/build_pods.go
- internal/fullnode/build_pods_test.go
- internal/fullnode/configmap_control.go
- internal/fullnode/configmap_control_test.go
- internal/fullnode/pod_control.go
- internal/fullnode/pod_control_test.go
Closes https://github.com/strangelove-ventures/cosmos-operator/issues/210
> fix(CosmosFullNode): Reboot pods on config changes

- api/v1alpha1/scheduledvolumesnapshot_types.go
- config/crd/bases/cosmos.strange.love_scheduledvolumesnapshots.yaml
- controllers/scheduledvolumesnapshot_controller.go
- internal/volsnapshot/status.go
- internal/volsnapshot/status_test.go
Closes https://github.com/strangelove-ventures/cosmos-operator/issues/274
> feat(ScheduledVolumeSnapshot): Allow user to suspend snapshots

- api/v1/cosmosfullnode_types.go
- config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
Closes https://github.com/strangelove-ventures/cosmos-operator/issues/309
> fix(CosmosFullNode): Allow 0 halt height

- api/v1/cosmosfullnode_types.go
- config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
- internal/fullnode/configmap_builder.go
- internal/fullnode/configmap_builder_test.go
- internal/fullnode/pod_builder.go
- internal/fullnode/pod_builder_test.go
- internal/fullnode/ports.go
Allows for easier switching between FullNode and Sentry.
> feat(CosmosFullNode): Add FullNode type in addition to Sentry

- .github/workflows/release.yaml
- Dockerfile
- local.Dockerfile
Cross compile and build for branches
> Docker image - cross compile

- config/samples/cosmos_v1_cosmosfullnode_penumbra.yaml
Add penumbra example of chain halt upgrade
> Add upgrade to penumbra example

- config/samples/cosmos_v1_cosmosfullnode_penumbra.yaml
Update penumbra sample config for mainnet
> examples(penumbra): Update sample

- Makefile
- config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
- config/crd/bases/cosmos.strange.love_scheduledvolumesnapshots.yaml
- config/crd/bases/cosmos.strange.love_statefuljobs.yaml
- config/rbac/role.yaml
Update controller gen version from 14 to 16.5
ran make generate manifests to update required files.
> chore: update controller gen version

- internal/fullnode/service_builder.go
- internal/fullnode/service_builder_test.go
This PR will supercede  work done by allthatJazz on #428.
Adding ordinal usage.
Next step testing on a vcluster in Strangelove's infra.
Tested and verfied creation of services.
> feat: privval service creation logic + conflict resolutions

- controllers/cosmosfullnode_controller.go
- internal/fullnode/labels.go
- internal/fullnode/mock_test.go
- internal/fullnode/node_key_collector.go
- internal/fullnode/node_key_collector_test.go
- internal/fullnode/pod_builder.go
- internal/fullnode/pod_builder_test.go
Fix node collector shadowing issue
Copy labels from the CRD to all created resources (pod, pvc, svc, etc)
> fix: node collector

- api/v1/cosmosfullnode_types.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
- internal/fullnode/service_builder.go
> feat: allow enabling additional service ports

- api/v1/cosmosfullnode_types.go
- config/crd/bases/cosmos.strange.love_cosmosfullnodes.yaml
- internal/cosmos/status_collector.go
- internal/fullnode/configmap_builder.go
- internal/fullnode/peer_collector.go
- internal/fullnode/pod_builder.go
- internal/fullnode/pod_builder_test.go
- internal/fullnode/ports.go
Allow custom p2p and rpc ports
> feat: customize comet rpc and p2p ports

- cmd/versioncheck.go
Allow successful `version-check-init` if directory doesn't exist by providing flag `-c`/`--continue`
Required for some use-cases with custom genesis init.
> feat: continue on version-check failure
